adafruit/circuitpython-org

_layouts/download.html
assets/sass/pages/_download.scss

The one change that differs from the mockup is that I updated the width of the select, as it looked better with some of the longer languages. I can revert it, but it was easy to get it to align well with the grid for all responsive sizes as well with this style.

Clean up styles on download page

---

assets/sass/pages/_downloads.scss
downloads.html

Sets all board images on the downloads page to a fixed aspect ratio, shrinking any images down to fit within a 4:3 box, center aligned.
Example:

Downloads Images Ratio

---

_data/files.json

`build_board_info.py` was unable to run with adabot credentials, so I ran it by hand and did this PR by hand. It's equivalent to the automated PR. Could someone review and approve to get beta.5 into circuitpython.org? Thanks.

update to beta.5; by hand due to travis cred issues

---

_layouts/download.html
assets/javascript/download.js

- Fixes language dropdown selection.
- Fixes language selection for multiple files.
- Fixes auto-loading of locale for setting language.

Language dropdown not working, also fixes multiple file selection

---

_layouts/download.html
assets/sass/pages/_download.scss

I'm currently linking to release notes on github releases page. Let me know if there is a better location for each version.
Fixes: https://github.com/adafruit/circuitpython-org/issues/54
Example:
https://github.com/adafruit/circuitpython/releases/tag/3.1.2

Add link to release notes on download page

---

_board/cp32-m4.md
_board/datalore_ip_m4.md
_board/feather_radiofruit_zigbee.md
_board/gb_m4.md
_board/pca10040.md
_board/sam32.md
downloads.html

Temporarily remove boards as listed in issue: #106.
New downloads_display flag in front matter on board files. If not set, boards will display. Set to false to exclude a board.
This also fixes the issue where boards like sam32 weren't properly linking to latest files and only showed the Browse S3 and Browse Github links.

Add flag to remove boards from downloads display

---

_board/circuitplayground_express_digikey_pycon2019.md
_board/gemma_m0_pycon2018.md

Added more information links to both PyCon 2018 and PyCon 2019 board pages.

Updated PyCon board pages

---

.gitmodules
.travis.yml

The next (last?) part to #119.
Two environment variables will need to be added to Travis:
- `ADABOT_GITHUB_ACCESS_TOKEN`: self explanatory
- `CP_ORG_UPDATER_RUN_DAY`: Sets the day of the week that the script will actually run. Day is a number between 0 & 6, with 0 being Monday. (Travis cron will be set to run daily. This ensures the script runs on the day we want since Travis won't guarantee that a weekly cron will run on a certain day.)
I was unsure that the `rvm` stuff in the original `.travis.yml` was necessary, since the `script` section is empty. If its not needed I can remove it. Also, I just thought about this: I could also exclude it from the daily cron, using the `$TRAVIS_EVENT_TYPE` env var if need be.

Add adabot For Auto-updating Libraries/Contrib Info

---

.travis.yml

After removing the matrix setup when dropping the `rvm` section in `.travis.yml`, I forgot to remove the `--user` flag from the pip install command. Which causes:
```
pip 19.0.3 from /home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/pip (python 3.6)
0.39s$ pip install --user -r adabot/requirements.txt
Can not perform a '--user' install. User site-packages are not visible in this virtualenv.
The command "pip install --user -r adabot/requirements.txt" failed and exited with 1 during .
```
This...fixes that. Me hopes. 🎲

Fix Travis Failure

---

_data/files.json

Automated website update for release 5.0.0-alpha.4 by Blinka.
New boards:
* pewpew_m4
* stm32f411ve_discovery
* stm32f412zg_discovery

Automated website update for release 5.0.0-alpha.4

---

.gitignore
README.md
_data/files.json

Pull request #286 was incomplete, it left "unknown" boards in the list.  This finishes removing Feather Huzzah and Feather nRF52832 from the index of boards.
Testing performed: Built locally and looked at the "downloads" page

Remove unsupported boards

---

_board/mini_sam_m4.md

The minisam.cc URL redirects to a 404'd page at minifigboards.com.
The new URL is the new order page on minifigboards.com.
Testing performed: built locally and clicked the link

mini_sam_m4: Update URL

---

libraries/contributing.html

.. by splitting the issue text at the first space, so that the URL doesn't include that part.

contributing: fix links which had '(### days)' in the URL

---

_includes/head.html

htmlproofer diagnosed this problem:
```
- ./_site/404/index.html
*  External link http://localhost:4000/feed.xml failed: 404 No error
```

For better or for worse, circuitpython.org doesn't have an RSS/Atom feed

---

.travis.yml

This should put `libraries.json` in the correct folder on S3, avoiding the `access denied` error.

Restructure Travis Artifact Paths To Address S3 Errors

---

.travis.yml

This fixes the S3 deployment, as it wasn't finding the generated `web/libraries.json`. 
The `ls web/*` step in the artifact deployment was searching for `adabot/web/*` since Travis changes the directory to run adabot.
I have tested this on a personal repo: https://travis-ci.org/sommersoft/aws_s3_testing/jobs/592865104
Lastly, this was so simple, it deserves a 🤦‍♂.

libraries.json: Fix S3 Deployment

---

_board/snekboard.md

Fix typo -- Leo -> Lego

---

.github/workflows/workflow.yml

Ever since the GitHub Actions workflow to build the site was put in, the cron job has also been running on my fork (I'm a beta participant in Actions).
Obviously, it fails since I don't have the secrets, which triggers a daily email about the failure. Its a minor nuisance, but once Actions availability increases this might get out of hand.
Unfortunately, the way that `schedule` events currently work, it cannot be limited itself. I tried on a rest repo.
This change will only run the `build` job if the repository is owned by Adafruit. I added a job to print out if the repository's owner is Adafruit; otherwise its just a blank completed run that constantly shows "Starting your workflow runs...".

Only Run the GitHub Actions Workflow On the Adafruit Repository

---

_data/files.json

Automated website update for release 5.0.0-alpha.5 by Blinka.
New boards:
* itsybitsy_nrf52840_express
* arduino_nano_33_ble
* serpente
* stringcar_m0_express
* sparkfun_qwiic_micro_no_flash
* circuitplayground_express_displayio
* sparkfun_qwiic_micro_with_flash
* pyboard_v11
* feather_stm32f405_express
* spresense

Automated website update for release 5.0.0-alpha.5

---

_data/files.json

Automated website update for release 5.0.0-beta.1 by Blinka.
New boards:
* shirtty
* pyb_nano_v2
New languages:
* ko

Automated website update for release 5.0.0-beta.1

---

_data/files.json

Automated website update for release 5.0.0-beta.2 by Blinka.
New boards:
* teknikio_bluebird
* xinabox_cc03
* xinabox_cs11
* stm32f411ce_blackpill

Automated website update for release 5.0.0-beta.2

---

assets/javascript/downloads.js
downloads.html

As suggested in #347, this adds a board counter for the downloads. Tested on my system locally with Jekyll. If it all looks good, I'll add the same to the Blinka page.

Added board counter for downloads

---

_data/files.json

Automated website update for release 5.0.0-beta.3 by Blinka.
New boards:
* clue_nrf52840_express
* feather_mimxrt1062
* imxrt1010_evk
* feather_mimxrt1011

Automated website update for release 5.0.0-beta.3

---

_board/openbook_m4.md

This was an oversight on my part; I didn't realize that the feature list was intended for tags and not freeform text. 
We could also add all the defined tags to template.md with a comment, which would clarify this for folks submitting new boards.

fix feature list for open book

---

_data/files.json

Automated website update for release 5.0.0-beta.4 by Blinka.
New boards:
* aramcon_badge_2019
* ohs2020_badge
* openbook_m4
* seeeduino_xiao

Automated website update for release 5.0.0-beta.4

---

template.md

@makermelissa asked me to open an issue for a suggestion I made in #380; I figured it would be easier to just make it a pull request. The learn guide for adding a board mentions the constraints on tags, but the README doesn't; I think adding instructions and the official tags to the template file would streamline this process for people adding new boards.

Clarify the features list

---

_blinka/orange_pi_lite.md
_blinka/orange_pi_one.md

Found missing quote mark in one and other referred to jpg instead of png.

Fixing Orange Pi Malformed files

---

_data/files.json

Automated website update for release 5.0.0-rc.0 by Blinka.
New boards:
* arduino_nano_33_iot
* pycubed
* circuitbrains_basic_m0
* circuitbrains_deluxe_m4
* sparkfun_samd51_thing_plus
* espruino_wifi
* stm32f4_discovery
* espruino_pico
* feather_m7_1011

Automated website update for release 5.0.0-rc.0

---

_includes/download/board.html

- Add S3 download button for Past Releases, since future releases will only have assets on S3.
- Update download blurbs.

Update Absolute Newest and Past Releases download info

---

_board/circuitplayground_bluefruit.md
_board/circuitplayground_express_crickit.md
_board/feather_m0_adalogger.md
_board/feather_m0_basic.md
_board/feather_m0_express_crickit.md
_board/feather_m0_rfm69.md
_board/feather_m0_rfm9x.md
_board/feather_m4_express.md
_board/feather_nrf52840_express.md
_board/feather_stm32f405_express.md
_board/gemma_m0.md
_board/grandcentral_m4_express.md
_board/hallowing_m0_express.md
_board/hallowing_m4_express.md
_board/itsybitsy_m0_express.md
_board/itsybitsy_m4_express.md
_board/itsybitsy_nrf52840_express.md
_board/metro_m0_express.md
_board/metro_m4_airlift_lite.md
_board/metro_m4_express.md
_board/monster_m4sk.md
_board/pirkey_m0.md
_board/pybadge.md
_board/pygamer.md
_board/pyportal.md
_board/pyportal_pynt.md
_board/pyportal_titano.md
_board/pyruler.md
_board/trinket_m0.md

Adding learn guide links to adafruit boards on Downloads page

---

_board/arduino_nano_33_ble.md

https://forums.adafruit.com/viewtopic.php?f=60&t=158279&p=803678#p803678 requested a prominent note about this.

Add note about UF2 bootloader being required for Arduino Nano 33 BLE

---

.github/workflows/adabot_cron.yml

Went to verify yesterday's Adabot update for `contributing/`, and saw that results are a day behind. Turn out that `adabot_cron.yml` takes longer than before, so while it runs fine it doesn't finish before the Jekyll build starts.
```
Contributing script:
- Started at: 4:45CDT
- Runtime: 20m 45s
Jekyll site build:
- Started at: 5:02CDT
```
This changes the `adabot_cron.yml` scheduled time to occur 45 minutes before the Jekyll build.

Adjust The Scheduled Time For adabot_cron.yml

---

_data/files.json

Automated website update for release 5.1.0-rc.0 by Blinka.
New boards:
* TG-Watch02A
* uartlogger2

Automated website update for release 5.1.0-rc.0

---

_includes/download/blinka.html

Fixes #393. This only shows the installation instructions when they are available.

Updated blinka details page to only show instruction when available

---

_board/TG-Watch02A.md
_board/uartlogger2.md

This will hide the Unknown boards until their authors want to provide some information.

Adding basic stubs to hide Unknown boards on website

---

_layouts/rss.html
feed.html

I went ahead and created an RSS feed that contains all the CP boards and Blinka boards. This is dependent on #439 being merged in first though because it uses the dates from those and the RSS reader should sort by those dates, otherwise it won't work.

Created RSS feed

---

_includes/head.html
_includes/header.html
assets/sass/layout/_header.scss
feed.html

I added an RSS icon that links to the new feed and updated the top menu spacing so it looked better with the new icon. I also added images to the description of the RSS items so that they should show up in the users' feeds and tested with NetNewsWire. Adding @jwcooper as a reviewer since it affects the styles.

Added RSS Icon + Added image to items

---

_data/bootloaders.json

@makermelissa please approve this right now while I investigate a bootloader bug report which could be a big issue

revert uf2 bootloader to 3.7.0 while testing

---

_data/bootloaders.json

- Update `atmel-samd` latest bootloader to v3.9.0. Bootloader updaters have been tested on Metro M0, Metro M4, and CPX.
- Add bootloader info for new boards `8086_commander` and `uartlogger2`.

Update atmel-samd bootloader to v3.9.0; add new bootloader boards

---

_board/feather_m0_rfm69.md
_data/bootloaders.json

fix trellis bootloader link; describe both 433 and 900 MHz Feather M0 RFM69 boards

---

_data/files.json

Automated website update for release 5.3.0-rc.0 by Blinka.
New boards:
* nfc_copy_cat
* nucleo_h743zi_2
* nucleo_f767zi

Automated website update for release 5.3.0-rc.0

---

_includes/download/blinka.html

Fixes #468. Download instructions weren't showing if non-existent, but still showed if empty. This fixes that.

Don't show instructions if blank

---

_board/nucleo_f746zg.md
_board/nucleo_f767zi.md
_board/nucleo_h743zi_2.md
_board/openmv_h7.md
_board/pca10100.md
_board/pitaya_go.md
_board/simmel.md
_board/stm32f746g_discovery.md
_board/teensy41.md
_data/files.json

Automated website update for release 5.4.0-beta.0 by Blinka.
New boards:
* simmel
* pitaya_go
* pca10100
* openmv_h7
* nucleo_f746zg
* stm32f746g_discovery
* teensy41
New languages:
* sv

Automated website update for release 5.4.0-beta.0

---

_board/circuitbrains_basic_m0.md
_board/circuitbrains_deluxe_m4.md
_board/espressif_saola_1_wroom.md
_board/espressif_saola_1_wrover.md
_board/fluff_m0.md
_board/nice_nano.md
_board/pycubed_mram.md
_board/simmel.md
_data/files.json
_includes/download/board.html

Automated website update for release 5.4.0-beta.1 by Blinka.
New boards:
* fluff_m0
* aloriumtech_evo_m51
* pycubed_mram
* espressif_saola_1_wrover
* espressif_saola_1_wroom
* hiibot_bluefi
* nice_nano
New languages:
* cs
* nl

Automated website update for release 5.4.0-beta.1

---

_includes/download/board.html
assets/javascript/download.js
assets/sass/pages/_download.scss

Alert message will only show for chrome and includes a link to disabling protection in safe browsing.

Added message for chrome users that displays info about blocked UF2s

---

_layouts/contributing.html
contributing/weblate.html

It looks roughly like this:
There are other widgets we could choose instead:
https://hosted.weblate.org/widgets/circuitpython/

contributing: Add weblate

---

assets/javascript/downloads.js

I have repeatedly been tripped up by wanting to enter a manufacturer name in the text search area.  While it is possible to open the filter panel and select manufacturers, it is more convenient and intuitive to simply enter this in the single text search box.
By concatenating several fields from the dataset (name, id, manufacturer, and features), and then searching that it becomes possible to text-search e.g., for "alligator" (board feature), "diary" (manufacturer) or "metro_m4" (board id).

downloads search: Enable text search on id, manufacturer, and features

---

_layouts/contributing.html
contributing/weblate.html

@jwcooper Tagged you to verify that I didn't break any HTML in moving things around. 
@jepler Please check the content changes and see if you like them. Feedback is welcome and appreciated.

Update Localization title and copy.

---

_board/ikigaisense_vita.md

I didn't notice until after it update on the site that I set the title was just the board ID.

Fixed title on Ikigaisense Vita

---

_data/files.json

Automated website update for release 6.1.0-beta.1 by Blinka.
New boards:
* adafruit_magtag_2.9_grayscale
* targett_module_clip_wroom
* targett_module_clip_wrover
* ADM_B_NRF52840_1
New languages:
* sv
* en_x_pirate
* ja
* en_US
* pl
* nl
* cs
* it_IT
* fil
* fr
* pt_BR
* es
* de_DE
* hi
* ko
* ID
* el

Automated website update for release 6.1.0-beta.1

---

_board/ADM_B_NRF52840_1.md
_board/blm_badge.md
_board/targett_module_clip_wroom.md
_board/targett_module_clip_wrover.md
assets/javascript/downloads.js

Fixes #601. This also hides some unknown boards until we can get them added and adds a missing date_added date to the BLM badge.

Fixed sorting and hid unknown boards

---

_data/files.json

Automated website update for release 6.1.0-beta.2 by Blinka.
New boards:
* cp_sapling_m0
* cp_sapling_m0_spiflash
* thunderpack_v12
* thunderpack_v11
New languages:
* ko
* nl
* ID
* hi
* cs
* sv
* es
* en_x_pirate
* fr
* pl
* de_DE
* pt_BR
* it_IT
* ja
* en_US
* fil
* el

Automated website update for release 6.1.0-beta.2

---

_data/files.json

Had to update version manually, due to change in `build_board_info.py` and structure of `_data/files.json`. Tried running new version in old tree, but ran into credential problems.
Also updated download counts, using December 2020 data.

manual release of 6.0.1

---

_data/files.json

Automated website update for release 6.1.0-beta.3 by Blinka.
New boards:
* stackrduino_m0_pro
* bastble
New languages:
* ja
* en_US
* el
* fil
* nl
* pl
* it_IT
* hi
* en_x_pirate
* fr
* ID
* ko
* pt_BR
* de_DE
* es
* cs
* sv

Automated website update for release 6.1.0-beta.3

---

_data/files.json

Automated website update for release 6.1.0-rc.1 by Blinka.
New boards:
* neopixel_trinkey_m0
* adafruit_feather_esp32s2_tftback_nopsram
* adafruit_feather_esp32s2_nopsram
* TG-Watch
New languages:
* ko
* ja
* pl
* en_x_pirate
* cs
* pt_BR
* de_DE
* ID
* nl
* el
* sv
* fr
* hi
* it_IT
* en_US
* fil
* es

Automated website update for release 6.1.0-rc.1

---

assets/javascript/download.js

When a user selects a language in a download menu:
- the language selected is memorized in the browser
- all language menus on the page are synchronized (if possible)
When a page is loaded
- the saved language is recovered and used to set the download menus
- if no language was saved it pulls the favorite languages from the browser as before
It's implemented with localStorage which seems more fitting to me for a static site, but could use cookies.
This also includes a fix to the selection of the menus' language. It now iterates on user languages in their order of preference to pick the best match.
Also, when the browser gives "`<language>-<region>`",  it first tries a full match, then tries to match `<language>` to the locales available on the site. And I tossed a couple of toLowerCase() …

Remember language selection and fix autoselection

---

_data/files.json

Automated website update for release 6.2.0-beta.0 by Blinka.
New boards:
* adafruit_feather_rp2040
* raspberry_pi_pico
* stm32f411ce_blackpill_with_flash
New languages:
* sv
* nl
* ko
* fr
* pl
* it_IT
* de_DE
* en_x_pirate
* hi
* pt_BR
* es
* en_US
* fil
* ID
* cs
* el
* ja

Automated website update for release 6.2.0-beta.0

---

Gemfile.lock

Ok, trying to decrypt the error message, I think what it is saying is that the dependency versions under github pages don't match, so I likely modified this in the wrong place, so I'm reverting that one change I did manually.

Revert github pages dependency changes

---

_data/files.json

Automated website update for release 6.2.0-beta.1 by Blinka.
New languages:
* ko
* es
* nl
* sv
* hi
* cs
* fr
* el
* ID
* ja
* en_US
* fil
* de_DE
* pl
* it_IT
* pt_BR
* en_x_pirate

Automated website update for release 6.2.0-beta.1

---

libraries/index.html

The text about the bundle was there, but there was no link.
This might be automated in the future, but fixing quickly for now.

remove 5.x bundle boilerplate

---

_data/files.json

Automated website update for release 6.2.0-beta.2 by Blinka.
New boards:
* dynalora_usb
* silicognition-m4-shim
* lilygo_ttgo_t8_s2_st7789

Automated website update for release 6.2.0-beta.2

---

_board/trinket_m0.md

Hi, I found a little typo on the Trinket M0 page. At the bottom, it says MO instead of M0. I hope I did this pull request right, I'm new to the more collaborative features of GitHub ;)

Fix typo in Trinket M0 page

---

_data/files.json

Automated website update for release 6.2.0-beta.3 by Blinka.
New boards:
* unexpectedmaker_tinys2
* pimoroni_tiny2040
* pimoroni_picosystem
* pimoroni_keybow2040
* qtpy_rp2040
New languages:
* en_GB

Automated website update for release 6.2.0-beta.3

---

_includes/download/board.html

The language menus are in an arbitrary order, making it potentially confusing when looking for one. The order used is the one from the files.json file, which in turn depends on the way languages are listed with `os.scandir` in the circuitpython repository (`build_board_info.py`).
The displayed language names are in the `board.html` template. To sort by name the code uses Liquid's {%capture%}  and split to make a new list with the name and the language code, so it can be sorted. This requires a little bit of manipulations to avoid whitespaces interfering with the sort.

Sort the language menus by language name

---

_data/files.json

Automated website update for release 6.2.0-rc.0 by Blinka.
New boards:
* rotary_trinkey_m0
* franzininho_wifi_wroom
* adafruit_funhouse
* franzininho_wifi_wrover
* sparkfun_nrf52840_micromod
* sparkfun_pro_micro_rp2040
* adafruit_qtpy_rp2040
* sparkfun_thing_plus_rp2040
* adafruit_itsybitsy_rp2040
New languages:
* en_GB

Automated website update for release 6.2.0-rc.0

---

Gemfile.lock

Reverts adafruit/circuitpython-org#660. kramdown 2.3.1 breaks github-pages-207. github-pages-214 fixes that but it has other changes. This is temporary.

Revert "Bump kramdown from 2.3.0 to 2.3.1"

---

_includes/downloads/board_image.html

Speeds up downloads and blinka page loading times on slower connections. Older browsers will just ignore the new attribute.
Browsers supported: https://caniuse.com/loading-lazy-attr

Lazy load images if browsers support the loading attribute

---

_board/atmegazero_esp32s2.md

I'm currently crowdfunding this version on GroupGets.com. The link was taking people to the older version which doesn't support circuitpython.

Updated the link to the correct place to order this version.

---

_board/muselab_nanoesp32_s2_wroom.md
_board/muselab_nanoesp32_s2_wrover.md

Here is the download page for the new CircuitPython build for the Muse lab NanoESP32-S2 w/WROVER.
This pull request also update the download page of the original NanoESP32-S2 that is now named NanoESP32-S2 w/WROOM.
For reference, the related PR in CircuitPython repo: https://github.com/adafruit/circuitpython/pull/4834

Added NanoESP32 S2 w/WROVER & reword WROOM version

---

_data/files.json

Automated website update for release 7.0.0-alpha.4 by Blinka.
New boards:
* espressif_kaluga_1.3
* pimoroni_pga2040

Automated website update for release 7.0.0-alpha.4

---

_data/files.json

Automated website update for release 7.0.0-alpha.6 by Blinka.
New boards:
* gravitech_cucumber_rs
* gravitech_cucumber_r
* gravitech_cucumber_m
* gravitech_cucumber_ms
* bluemicro840
* raytac_mdbt50q-rx
* sparkfun_stm32f405_micromod

Automated website update for release 7.0.0-alpha.6

---

_includes/header.html
_includes/header_mobile.html
libraries/index.html

I did some rewriting on the libraries page:
- Added link to readthedocs for all libraries.
- Reworked the .mpy explanation and other text.
- Added link to Libraries page in Welcome guide in two places
- Mentioned CircUp.
- Mentioned and linked to the Community Bundle. This could be expanded later.
- Redid headings a bit
I also revamped the top links a bit, renaming "API to "Documentation" "Help" to "Forums", and labelling the Discord and RSS links more explicitly.
The mobile header was also updated.
OLD:
NEW:
Fixes #53 
Fixes #526 
Fixes #633
I tested the HTML and the looks locally.

update libraries page and header links

---

_data/files.json

Automated website update for release 7.0.0-beta.0 by Blinka.
New boards:
* morpheans_morphesp-240
* odt_pixelwing_esp32_s2
* ai_thinker_esp_12k_nodemcu
* crumpspace_crumps2
* pimoroni_interstate75
* pimoroni_plasma2040

Automated website update for release 7.0.0-beta.0

---

_data/files.json

Automated website update for release 7.0.0-rc.1 by Blinka.
New boards:
* unexpectedmaker_feathers2_neo
* lolin_s2_mini
* espressif_hmi_devkit_1
* warmbit_bluepixel
* adafruit_led_glasses_nrf52840
* jpconstantineau_encoderpad_rp2040

Automated website update for release 7.0.0-rc.1

---

_board/lolin_s2_mini.md

Probably this PR should remain on hold until `tinyuf2-lolin_s2_mini-...zip` with `combined.bin` is available at https://github.com/adafruit/tinyuf2/releases ([PR#142](https://github.com/adafruit/tinyuf2/pull/142), but latest release was on 2021-07-30). For review in any case.

Lolin S2 Mini board download page updates, features & TinyUF2 flashing instructions

---

.github/workflows/build.yml

This reduces the tokens we need to manage and uses one scoped to this repo.

Switch to GITHUB_TOKEN for deploy

---

_board/lolin_s2_mini.md
_data/bootloaders.json
_includes/download/board.html

Fixes #752
Checked for typos, tested with `bundle exec jekyll serve`, and verified that download links are correctly generated on the Lolin S2 Mini page. Have not manually tested the other affected 21 pages for ESP32-S2 boards, but mappings in bootloaders.json should be correct.

Add "Install/Repair UF2 Bootloader" section for ESP32-S2 boards

---

_board/lolin_s2_mini.md

Low-priority.
I'm happy to templatize this and other MCUs, modules, other components, etc., for consistency on board pages, and for anything that might be useful in the "Downloads" search field.
For search perhaps by using the same mechanism as, e.g., `data-id="feather_nrf52840_express"` ... `data-features="Feather-Compatible,Battery Charging,Bluetooth/BTLE,Breadboard-Friendly"` and adding a `data-mcu` or `data-components` field to include things like `nrf52840` or `ESP32-S2FN4R2`, and/or other components, particularly useful for searching when MCU/component names do not appear in `data-name` nor elsewhere.

Lolin S2 Mini - added more specs useful for makers

---

_board/lolin_s2_mini.md

Putting a note on the S2 Mini page about an error on the silkscreen markings on v1.0 of the board.
GPIO12 and 13 are reversed from what they should be.

Note error on Lolin S2 Mini v1.0 board silkscreen

---

assets/sass/pages/_download.scss

- Fixes #764.
Change unstable and unrecommended download links to purple, to avoid confusion that the links are not functional.
I left the markers in, in case we want to change the link colors again, in the future. Also, I did not change the language dropdown away from gray.

Change .unstable and .unrecommended links to purple

---

libraries/index.html

The link for the Community Bundle pointed to the Circuitpython Organisation Bundle (which should probably get a link too some day).

Fix community bundle link

---

_board/pca10059.md
_board/pca10100.md

Renamed the "Manufacturer" for 2 boards to match the actual name of the manufacturer.
Both the PCA10059 and PCA10100 had only "Nordic" as manufacturer while the PCA10056 had "Nordic Semiconductor"
This caused the 3 boards to show up as 2 different manufacturers in the list of filters, which obviously is redundant and incorrect.

Renamed Nordic to Nordic Semiconductor for 2 boards

---

_data/files.json

Automated website update for release 7.1.0-beta.1 by Blinka.
New boards:
* raspberrypi_pi4b
* raspberrypi_zero2w
* raspberrypi_cm4io
* adafruit_qtpy_esp32s2
New languages:
* ru

Automated website update for release 7.1.0-beta.1

---

_board/fomu.md

The quote causes issue with sorting. This was the quick fix.
Should be able to close out: https://github.com/adafruit/circuitpython-org/issues/524

Rename manufacturer to remove single quote

---

libraries/index.html

6.x bundle building was stopped by https://github.com/adafruit/circuitpython-build-tools/pull/83. This removes explicit listing of the 6.x bundles, and adds links to the last bundle built for a particular version.

Remove 6.x bundle links; add pointer to obsolete bundles list

---

_data/bootloaders.json

TinyUF2 is now at 0.7.0, and Adafruit_nRF52_Bootloader is now at 0.6.3.

Update bootloader versions to latest

---

_board/microbit_v2.md
_board/microdev_micro_c3.md
_board/microdev_micro_s2.md

These had three hash marks before "Contribute". Other headings in these files may also have had "###" where "##" is usual, further review wouldn't hurt.

Get some straggling 'contribute' headers removed

---

_board/jpconstantineau_encoderpad_rp2040.md
_board/jpconstantineau_pykey18.md
_board/jpconstantineau_pykey87.md

This PR makes PyKey18 and PyKey87 visible on the download page as well as updates the product link for the CNC Encoder Pad RP2040 as it didn't point to the product itself.

Minor Pykey Updates (Links and enabling visibility)

---

_board/raspberrypi_zero_w.md

Watching this on https://circuitpython.org/board/raspberrypi_zero_w/ make me remove that line that make no sense.

Fixing "Zero 2 W" vs "Zero W"

---

_data/bootloaders.json

Updated to reflect https://github.com/adafruit/uf2-samdx1/releases/tag/v3.14.0. This new release just supports more boards: no bootloader update is needed or desirable for existing boards.

Update SAMD UF2 bootloader to v3.14.0

---

_data/files.json

Automated website update for release 7.2.0-alpha.2 by Blinka.
New boards:
* diodes_delight_piunora
* raspberrypi_zero
* raspberrypi_zero_w
* espressif_esp32s2_devkitc_1_n4r2
* unexpectedmaker_pros3
* espressif_esp32c3_devkitm_1_n4
* espressif_esp32s3_devkitc_1_n8r2
* adafruit_qtpy_esp32s3_nopsram
* unexpectedmaker_tinys3
* unexpectedmaker_feathers3
* adafruit_esp32s2_camera
* espressif_esp32s3_devkitc_1_n8r8
* espressif_esp32s3_devkitc_1_n8
* waveshare_rp2040_zero
New languages:
* tr

Automated website update for release 7.2.0-alpha.2

---

_board/lolin_s2_pico.md

The feature list is now a bit shorter. The details were a bit extensive from my point of view and mostly covering the ESP32-S2FN4R2 and not so much the S2 Pico itself.

Compress features list and add links to details

---

_board/metro_m0_express.md
_board/metro_m4_airlift_lite.md
_board/metro_m4_express.md
_board/metro_m7_1011.md
_board/metro_nrf52840_express.md

Remove whitespaces from lists and add specs for M7.

Update specs listing

---

_board/cytron_maker_nano_rp2040.md
_board/cytron_maker_pi_rp2040.md

Remove "marketing content" and try to stay on point. Remove repetitions.

Reduce content and update specs

---

_board/nice_nano.md

Source: https://docs.nicekeyboards.com/#/nice!nano/?id=nicenano

Add content

---

_board/adafruit_qtpy_esp32s3_nopsram.md

Just changing the obvious confusion between ESP32-S2 and ESP32-S3...
But maybe the first YouTube video need to be removed, it does not seems to talk about ESP32-S3 but only about ESP32 and playing doom or game emulation.

This is ESP32-S3 not ESP32-S2

---

_board/lilygo_ttgo_t8_s2_st7789.md

TTGO T8 ESP32-S2 is now also [supported](https://circuitpython.org/board/lilygo_ttgo_t8_s2/).

Remove reference to TTGO T8 ESP32-S2

---

_board/adafruit_qtpy_esp32s2.md

I am trying to make this more neutral and applicable to both the build-in antenna and the uFL connector version.
(I wish Adafruit could produce a picture that show both product next to each other for use on this page)

Tentative to show this also for uFL version

---

_data/bootloaders.json

Changelog for 0.8.0
* Rename board lolin_s2-pico to lolin-s2_pico (match CircuitPython board)
* NXP SPSDK for MIMXRT builds
* add custom esp32s2 board
* fix double tap issue
https://github.com/adafruit/tinyuf2/releases/tag/0.8.0

Set to latest TinyUF2 release 0.8.0

---

.github/workflows/build.yml
_board/adafruit_qtpy_esp32s2.md
_board/diodes_delight_piunora.md
_board/raspberrypi_zero.md
check-features.py

Before this, people were requested to follow a set list of features, but we had no automated check for it. Do this as a step of the CI, or a step that can be run locally.
I found several boards that had non-standard features listed; I corrected or deleted them as I saw appropriate.
There are also a number of boards without any features: blocks. I did not attempt to fix this. However, if this were fixed we could add an additional check in this script for future boards. However, this assumes every board has at least one feature in the list of features, which may not be true.

Check features at build time

---

_data/files.json
_includes/download/board.html

This lists the frozen modules below the built-in ones on boards pages.
Also includes a fix of files.json to replace frozen dir names with actual module names, [as mentioned here](https://github.com/adafruit/circuitpython-org/issues/684#issuecomment-1100794905).
The (?) link points to [the glossary's short paragraph on frozen modules](https://docs.circuitpython.org/en/latest/docs/reference/glossary.html?highlight=frozen#term-frozen-module).
Another possibility was [the frozen modules page in the "building circuitpython" guide](https://learn.adafruit.com/building-circuitpython/adding-frozen-modules).
It would be nice to have a more end-user-oriented reference on frozen modules, explaining that they take precedence over the lib directory, and how to replace them with a newer version (by …

List frozen modules in the download page

---

_board/hiibot_iots2.md
_data/bootloaders.json

`tinyuf2` 0.9.2 was released, adding the Hiibot IoTS2 files to the assets.

Add IoTS2 firmware ID and bump tinyuf2 version

---

assets/sass/pages/_contributing.scss
contributing/open_issues.html

Fixes #646. I attempted to use `:after` style css labels first, but css spec only allows 1 `:after` per item, so this was the best approach to display multiple tags.

Display issue labels for open issues

---

_board/pimoroni_picosystem.md

New note appears on the download page for this device here:

add note about how to enter bootloader mode for picosystem

---

_config.yml
assets/javascript/downloads.js

this will cause the search input on the downloads page to automatically focused when the page loads, so user can begin typing immediately.
I've also added `.idea` to the exclude list inside of `_config` file because I noticed that the test server command `bundle exec jekyll serve` was noticing changes inside of `.idea` that my IDE is making and using it as a trigger to regenerate all of the pages for the project even though that change it noticed isn't actually related to the project itself.

autofocus downloads search and exclude .idea directory

---

_board/adafruit_feather_esp32s3_4mbflash_2mbpsram.md
_data/bootloaders.json

Fixes the bootloader_id for Feather ESP32-S3 4MB Flash 2MB PSRAM.
Bump tinyuf2 from 0.9.2 to 0.9.4 as required.
https://github.com/adafruit/tinyuf2/releases/tag/0.9.3

Fix Adafruit Feather ESP32S2 bootloader id and bump tinyuf2

---

_board/lolin_c3_mini.md

The live version says this has an OLED, that's not true. I made minor modifications to Wemos's own description of the board [here](https://www.wemos.cc/en/latest/c3/c3_mini.html)

Update subheader/brief description of board

---

_includes/download/board.html

Fixes #1001.
Caution users to refer to board documentation to update or install UF2 bootloader.
Describe how to enter UF2 bootloader.

Improve ESP32-nn bootloader installation instructions

---

_board/lolin_s2_mini.md

Wrong infromation how to enter UF2 bootloader.
No propose changes button exist for "Install, Repair, or Update UF2 Bootloader" section on page 
https://circuitpython.org/board/lolin_s2_mini/

Wrong information how to enter UF2 bootloader

---

_board/Seeed_XIAO_nRF52840_Sense.md
_board/seeeduino_wio_terminal.md
_board/seeeduino_xiao.md
_board/seeeduino_xiao_kb.md
_board/seeeduino_xiao_rp2040.md

Seeed Studio is making a naming change on the XIAO serie of board, so I adapted 3 boards (skipping "Seeeduino XIAO - Keyboard Optimized")
https://www.seeedstudio.com/blog/2022/07/06/notice-on-product-name-change/

Seeed Studio is making a naming change on the XIAO serie

---

assets/javascript/download.js
downloads.html

resolves #1025 
- adds `?unknown_id=...` to the unknown boards URL
- the javascript on the board page looks for it
- sets the title (and html title) by replacing underscores with spaces and uppercasing the first letter
- replaces "unknown" with the ID in the URLs href, making them point to the right place

Generate the S3 link for inkown boards using URL query string

---

_board/lolin_c3_mini.md

8.0 is a major release (even if in Beta), so that part of the description does not make sense anymore.

Lolin C3 is available in CP 8.0

---

_board/elecfreaks_picoed.md

Should we consider a 7x17 LED matrix to be a display?
I believe only LCD or OLED display should be tagged as having a display.
However I added the Alligator Clip friendly as it looks like a Micro:bit.

ELECFREAKS Pico:ed have a display but also Alligator Clip

---

_board/beetle-esp32-c3.md
_board/matrixportal_m4.md
_board/pimoroni_interstate75.md
template.md

This beetle-esp32-c3 board has a connector so that you can attach a display sold separatly.
Do we consider that a display?
From the documentation:
* "Besides, the onboard easy-to-connect GDI saves the trouble of wiring when using a screen."
* "Comes with expansion board, more convenient to make projects or use with a screen"

Boards without a "Display" but with a "connector" for one.

---

_board/raspberrypi_cm4.md
_board/raspberrypi_cm4io.md
_board/raspberrypi_pi4b.md
_board/raspberrypi_zero.md
_board/raspberrypi_zero2w.md
_board/raspberrypi_zero_w.md

This adds more obvious warnings (and fixes grammar a bit) that the broadcom builds are very alpha and have significant issues. I've encountered this as a support issue several times recently. It's in the release notes but those are often not read.

Make it clearer that broadcom builds are very alpha

---

_board/raspberry_pi_pico_w.md
assets/javascript/downloads.js
downloads.html

Added tags and module search feature

---

_layouts/download.html

Fixes #1104. The `page.path` variable has the folder, exact filename, and extension, so it really simplifies things.

Fix edit page link

---

_includes/download/board.html

The previous link went to a version that wasn't being maintained and had a banner directing users to a different tool. Replace with a link to the version of ESP Web Flasher hosted on adafruit.github.io.

Replace link for ESP Web Flasher

---

.github/workflows/build.yml

.. it looks like the non-string value `3.0` was probably being interpreted as `3` aka `3.x`?
Previously it looks like we built with 'ruby 3.1.3p185 (2022-11-24 revision 1a6b16756e) [x86_64-linux]' so I chose to pin at "3.1"

Pin ruby at 3.1.

---

_board/luatos_core_esp32c3.md

There are 2 versions of this board differing in what is connected to the USB-C port. This PR clarifies that the board definition is intended to target the newer version using the ESP32-C3 built-in USB-CDC/JTAG pins rather than via a CH343 UART to USB chip.

Clarify which version of Luatos Core ESP32-C3 board is targeted

---

_board/luatos_core_esp32c3.md

GPIO11 on the ESP32-C3 is by default dedicated as the VDD pin for external SPI flash.
This board does not use the pin for that purpose, instead directly connecting flash VDD to the 3.3V bus and breaks the GPIO out to a board pin. In order to actually use it as a GPIO in Circuitpython requires setting an efuse on the chip (and beyond that will require modifications to ports/espressif/common_hal/microcontroller/Pin.c) and building a custom image. I removed the GPIO from pins.c in https://github.com/adafruit/circuitpython/pull/7372
This PR documents that information in the notes section.

Document the use of GPIO11 on the Luatos Core ESP32-C3 board

---

_includes/download/board.html

Clarify the text about releases on board download pages.
I tried testing this locally on Ubuntu 22.04 per the README, but could not get a working version of ruby. The regular package does not have OpenSSL support. `rvm` compiles fail for various versions, and `snap` installs don't work either: the compiles of `statemachine` either have version issues or `gcc` compilation issues. It was kind of a nightmare. Perhaps if someone has a setup that works they could pull this and see that the compiled pages look OK.

Clarify the kinds of releases

---

assets/javascript/download.js
cpinstaller/src/base_installer.js
cpinstaller/src/cpinstaller.js

This also sets it to use Amazon S3 for the download link for now to get around some CORS problems that cloudfront is causing and the "CircuitPython Installer" title is moved out of the base installer and into the CP specific one.
Also, uncommented some steps for the Bin file install so that it erases the chip first.

Update Installer to use selected language

---

cpinstaller/src/cpinstaller.js

Just tested the C3 now that the installer is working again and realized it should have been included in the list of boards without native usb.

Update Installer to treat C3 chips as not having Native USB

---

_data/bootloaders.json

3.15.0 has brownout protection on SAMD21. (typo in commit msg: should be 3.15.0)

Update atmel-samd bootloader to version 3.15.0

---

generate-board-info.py

Found a bug while trying to use the file where the bootloader was always null. Apparently it was looking in the wrong place in the bootloader json file.

Fix starting bootloader json key for gen board info script

---

_board/deneyap_kart.md
_board/deneyap_kart_1A.md
_board/deneyap_kart_1A_v2.md
_board/deneyap_kart_g.md
_board/deneyap_mini.md
_board/deneyap_mini_v2.md

Fix the problem about not listing .bin or .uf2 file when clicking "Browse S3" button on own page of the board because of naming style of Deneyap boards. 
Delete contribute section.

Change Naming Style of Deneyap Boards

---

_board/vcc_gnd_yd_rp2040.md

This is a small formatting change.
The current description contains full width parentheses `（）`. They aren't intended for English text and were probably left in when translating from Chinese. These are changed to half width `()`.
Additionally two periods are removed from the list of improvements for consistency within the list.

Fix fullwidth parentheses in YD-RP2040 board description

---

_board/adafruit_feather_rp2040_epd.md
_board/adafruit_feather_rp2040_thinkink.md
_data/files.json

Fixes #1199. Apparently in the previous releases it was called `adafruit_feather_rp2040_epd`, but in future releases will be called `adafruit_feather_rp2040_thinkink` because of https://github.com/adafruit/circuitpython/pull/7927. I had to change it to `adafruit_feather_rp2040_epd` for now, but it will need to be reverted on the next release.

Fix download links for RP2040 Feather ThinkInk

---

_includes/download/board.html

The nRF bootloader update blurb referred to the README in the bootloader repo. There are now guide pages for this that are more comprehensive, so point to them.

refer to guide pages for nRF bootloader updates

---

_includes/download/board.html

Put a warning to to update the bootloader on nRF boards right in the download box for CircuitPython, not just in the bootloader box.
Not everyone reads the release notes before updating. This will save support time.

include more prominent warning to update bootloader on nRF boards

---

_board/waveshare_esp32_s3_pico.md

Updating board name because the name here does not match in circuitpython repo.

Renaming waveshare_esp32s3_pico.md to waveshare_esp32_s3_pico.

---

_board/raspberry_pi_pico_w.md

BLE support on Pico W is not currently actively being worked on. Remove "coming soon" language and remove BLE as a feature. See https://github.com/adafruit/circuitpython/issues/7693.

Don't promise BLE for Pico W

---

_board/espressif_esp32c6_devkitc_1_n8.md

Fixes #1271. Espressif and their confusing names...

Fix board name for ESP32-C6-DevKitC-1-N8

---

_board/espressif_esp32c6_devkitm_1_n4.md

Title and name entries indicate S3 not C6.

Title and name entries indicate S3 not C6: espressif_esp32c6_devkitm_1_n4.md

---

.github/workflows/build.yml
Gemfile.lock

This appears to mostly be a duplicate, but a dev version. I think this will make it so actions stops failing.

Remove dev version of google-protobuf from Gemlock

---

Gemfile.lock

I think this may fix the error during actions:
```
/opt/hostedtoolcache/Ruby/3.3.0/x64/lib/ruby/3.3.0/logger.rb:384:in `level': undefined method `[]' for nil (NoMethodError)
@level_override[Fiber.current] || @level
^^^^^^^^^^^^^^^
from /home/runner/work/circuitpython-org/circuitpython-org/vendor/bundle/ruby/3.3.0/gems/jekyll-4.3.2/lib/jekyll/log_adapter.rb:45:in `adjust_verbosity'
```

Update jekyll to fix an incompatibility with logger

---

assets/javascript/downloads.js

This turns the search function into more of a 'fuzzy search': The search is expected to be a series of space-separated terms, but the terms can appear in any order, can be just part of a word (e.g., "uefr" would match "bluefruit") and with other terms between them.
So for instance after this change both "tft feather" or "feather tft" will show the Feather ESP32-S3 TFT PSRAM (as well as 3 other feather boards)
Closes #1321

Improve search

---

_board/adafruit_esp32s3_camera.md

I believe this will resolve the broken link...
Fixes #1324 adafruit/circuitpython#8903

Change bootloader link to match tinyuf2 repository

---

assets/javascript/downloads.js

Current searching and filtering login implementation uses regexes, which leads to performance issues. If someone would type quickly "matrixportal", the search bar would hang on e.g. 8th character for a moment and then continue to render.
Additionally, current regex makes it that "bit matrix" and "matrix bit" produce different result, which i believe is not intended. 
Overall, this change speed up filtering (in my case, on my computer) from 400-700ms to 2-5ms and produces same results no matter the order of terms in search field.
🏗️ Refactor:
- Function `shouldDisplayDownload` that determined whether to show or not a card with board now uses string based logic instead of regex
Easy way to test this is simply copy-paste the function to console in browser and the search bar will use it from …

Refactor of search function from regex to string based, massive speedup in searchbar performance 

---

_board/seeed_xiao_esp32c3.md

Add reference to https://learn.adafruit.com/circuitpython-with-esp32-quick-start/overview since ESP32C3 chips don't get installed or used the same was as typical cp devices.

Update seeed_xiao_esp32c3.md to refer to installation guide

---

_board/teensy40.md

The Teensy 4.0 board was incorrectly tagged as part of the STM chip family.

Correct chip family for Teensy 4.0

---

_board/espressif_esp32s3_box_lite.md
_board/lilygo_tdisplay_s3.md
feed.html

resolves #1354 
After this change there were two devices showing up at the top of the list (out of chronological order) It turns out the date parsing format is very specific, it needs 4 digit years and zero padded single digits, with those changes these devices now get put into the proper place of the order.
Worth considering breaking out the Blinka boards as a separate feed. Right now they effectively get rendered one after another in the same giant RSS feed. This means they won't ever appear at the top of the feed for any RSS client that doesn't do it's own sorting locally on pubDate. Or another option is to try to intermix them into 1 list, and then sort that and render it as the RSS feed, I'm not certain if it's possible but can check into it if that is something that other folks …

sort rss feed with newest at top

---

_includes/downloads/board_image.html

I noticed while testing the other RSS feed changes that the images weren't loading successfully (at least in the client app I tested which was FeedR on Android). They appeared as "broken image" icons.
Inspecting the code of the feed item within the app revealed that the image URLs were relative rather than absolute. When the page gets rendered in an HTML page that works fine because the client browser will know it's relative to the host of the page being viewed. 
I don't know if RSS spec includes something about relative URLs within feed items pointing back to the host of the feed source, but in this app that doesn't appear to occur automatically. 
Adding a hardcoded portion to the URL with the host allows those images to load successfully.
Originally I had hoped there was some way to …

fix image URLs in the RSS feed.

---

_data/bootloaders.json

Bumping ESP32-S2 and ESP32-S3 bootloader versions.
Check https://github.com/adafruit/tinyuf2/releases/tag/0.18.2

bump esp32s2 & esp32s3 bootloader version

---

_includes/downloads/board_image.html

This allows a `localhost:4000`-style URL to be generated for local testing, but still gives an absolute URL, which enhances compatibility with RSS readers. A comment is added explaining the reason for the absolute URL.
Closes #1374

Generate absolute URLs automatically

---

_board/waveshare_esp32_s3_geek.md
_board/waveshare_rp2040_geek.md

@jvprat spotted some mistakes in the new Waveshare RP2040-GEEK and ESP32-S3-GEEK devices. The RP2040 device does not support WiFi and neither board has a USB-C port. While double checking the feature list I also realized that the board does have a Stemma QT compatible connector so I added that feature as well.

Fix the feature list for the two Waveshare -GEEK boards

---

.github/workflows/build.yml

updates remaining action that needed update to Node.js 20. See https://github.com/peaceiris/actions-gh-pages/issues/1070.

Update to peaceiris/actions-gh-pages@v4

---

_board/espressif_esp32s3_devkitc_1_n8r8_hacktablet.md

The title and name of this board was mistakenly "ESP32-S3 Box". I think this was copy-pasta.

Correct name of ESP32-S3 HackTablet

---

tools/check-boards.py

The message will now say e.g.,
```
2021-1-21 is an invalid date for example-board. The format must be YYYY-MM-DD, using leading zeros if necessary
```

check-boards: show the correct format in the error message

---

assets/javascript/downloads.js

- Addresses #1438 
Some boards uses a hyphenated name for the microcontroller chip or other feature, and some do not. Right now the search will give different results in the two cases. For instance, searching for "ESP32C6" yields different results than "ESP32-C6".
This change makes the match ignore hyphens, producing a more inclusive search.
We used to use a regexp, which would have made for an easy fix, but that was too slow (see #1328), so this is "hand-coded".
Tested locally.
@Carla-Guo FYI

match hyphenated or unhyphenated search terms

---

_board/waveshare_rp2040_pizero.md
_board/waveshare_rp2040_zero.md

Board Waveshare RP2040-Zero was deleted by:
https://github.com/adafruit/circuitpython-org/commit/6ec46b6a51823d7e134d964288428a9df6fa1f4e#diff-12e6a57bd2b4284f5f5f93d010e3d3ecd0aafe75a5c10991432549441c27f873
Where file `_board/waveshare_rp2040_zero.md` was moved to `_board/waveshare_rp2040_one.md`.
Also, the board Waveshare RP2040-PiZero is not to be confused with Waveshare RP2040-Zero.
This commit gets that fixed by:
- Fixing Waveshare RP2040-PiZero title and name.
- Restoring Waveshare RP2040-Zero board information.

Restore deleted Waveshare RP2040-Zero

---

_includes/download/board.html

This turns the library list on board pages into clickable docs links.
It supports having class links like busio.SPI and frozen modules.
There were a few modules that don't have docs (_asyncio for example), and one frozen module (adafruit_connection_manager) that doesn't follow the expected path (it's just connectionmanager), but ignoring that it's working well.
Context from discord:
> I was going to add the links to the modules lists on boards pages (after imaginging they existed earlier 😁 ). I've got that sorted but the frozen modules are more tricky, mainly removing adafruit_ from the name and sticking after https://docs.circuitpython.org/projects/ works, e.g. https://docs.circuitpython.org/projects/display_text but not for connection_manager as it's page is without the underscore. Can …

Turn libraries list on board pages into links

---

.github/workflows/build.yml

Missed this in the previous PR to update to Node.20. This should get rid of the last warning we're seeing on the builds.

workflows/build.yml: update to actions/checkout@v4

---

_board/lolin_s3_pro.md

Fixes #1450. There is no lolin_s3_pro, but @marcobrianza has successfully used the lolin_s3 bootloader.

Fix lolin s3 pro bootloader

---

_board/sunton_esp32_2432S028.md

Changes:
- Added additional information about the possible need to hold BOOT button while programming.
- Added info about touch and display driver ICs as these can be difficult to find on product pages for this board.
With a board sourced from Banggood, I found that I had to hold down the BOOT button while programming. I also added information on the display driver and touch driver ICs used as this information can be difficult to find on seller's websites.
I think this additional information will be beneficial to users who may be unfamiliar with this board, as I was.

Updated sunton_esp32_2432S028 info for new users

---

_board/makerfabs_tft7.md
_board/sunton_esp32_2432S028.md

This just adds information regarding the board variant options that can be adjusted in settings.toml for the Sunton ESP32_243S028 and Makerfabs_tft7 boards.

Document settings.toml parameters for Sunton_2432S028 and Makerfabs_tft7

---

_board/makerfabs_tft7.md

The asterisk character in the screen resolution and interface listing gets interpreted as a formatting instruction messing up the output. This replaces the '*' with an 'x'.

Makerfabs_tft7: replace asterisk with 'x'

---

_board/circuitart_esp32s3_zero.md

This board_id didn't match the core repo which broke the download link for this board, and added a 2nd "unknown" instance to the downloads listing.
I tested this fix locally and it seems to resolve the issue, leaving only a single instance listed and the firmware download buttons work now

update board_id for circuitart zero s3

---

_board/lolin_s2_mini.md

Resolves: #1268 
Added note about no labels on silkscreen and which pins are configured by default

add note about lolin s2 mini SPI and I2C pins

---

_includes/download/board.html

Devices that have downloads for both will list the UF2 download above the BIN download with this change.

swap the .BIN and .UF2 download buttons

---

_board/adafruit_feather_huzzah32.md
_includes/download/board.html
assets/sass/pages/_download.scss
template.md

Resolves: #1034 
Make the `download_instructions` metadata field valid for CircuitPython core in addition to Blinka. If it has a value add a button linking to it to the download page.
I've only added the metadata to a single esp32 so far, but the rest of them could get updated to point to this guide if the way this has been added looks okay.

installation instructions button

---

_includes/download/board.html
assets/sass/pages/_download.scss

Resolves: #1035 
I added them below the built-in modules inside of purple "tag" elements. 
The do not currently do anything when clicked. 
This was my interpretation of the "little boxes" mentioned in the linked issue. I am open to feedback on the style or placement of them.

show features on board download page

---

_board/adafruit_feather_huzzah32.md

Update the 'how to install' link to the device specific guide page for huzzah 32 feather.

update huzzah how to install link

---

_includes/download/board.html
assets/sass/pages/_download.scss

And changed the features list to use the modules styling as mentioned in the discussion in #1524.
I found information from the liquid docs here: https://shopify.github.io/liquid/tags/iteration/ that ultimately led to a fix for the extra commas issue. 
The extra spaces before the comma seem to be caused by the closing of `</a>` on the next line instead of the some one as the contents.

Fix modules extra comma and spacing 

---

_board/circuitplayground_express_displayio.md
_board/edgebadge.md

A few more to follow up on comments from #1529 
ty @makermelissa for the cpx + displayio link.
I've added the EdgeBadge firmware button as an option on the pybadge learn guide page as well and added a link to that for the edgebadge file here.

cpx+displayio & edgebadge

---

_data/bootloaders.json

Resolves an issue reported on discord by @dglaude. https://discord.com/channels/327254708534116352/327298996332658690/1306026424183816222
Updates the nrf bootloader version to match the latest one linked in the guide pages about updating bootloader.

update nrf52840 bootloader version

---

_board/m5stack_m5paper.md

Family is `esp32s3`, should be `esp32`. Caused a spurious "Update bootloader" section on the board page.

Fix M5Paper family

---

_board/raspberry_pi_pico2.md
assets/javascript/downloads.js

Resolves: #1536 
This changes makes it so that exact matches on tags will get higher priority in the resulting list of boards. It adds "pico 2" to the pico 2 tags so that it will appear as the first result for "pico 2" now.

exact match tags search

---

assets/javascript/downloads.js

Resolves: #1540 
The new search logic broke the page by assuming that `downloadsSearch.searchTerm` would not be `undefined` which was an unsafe assumption and caused the rest of the JS to stop when an error was thrown. Its now wrapped in logic that ensures it isn't undefined or null before attempting to access properties. 
This also includes a fix for a seperate issue I noticed were after you search for something and then erase it from the search box you are left with the page in a very strange order that doesn't match the default sorting order. This turned out to be due to every device matching to the search term of empty string. The logic now ignores the empty string as a search term.

fix filtering for null search term

---

.github/workflows/build.yml

Fixing only the ruby major version number has been a repeated problem for google-protobuf, which comes precompiled and lags in support for new ruby releases.
Instead, install a known good ruby minor version 3.3.
Closes: #1556

pin ruby minor version

---

libraries/index.html

Change 'appropiate' to 'appropriate'.

Fix typo in index.html

---

_board/espressif_esp32_devkitc_v4_wroom_32e.md

The human-readable name and title of this board were wrong.
(Stumbled on this due to https://github.com/adafruit/circuitpython/issues/9960)
Also I removed some obsolete verbiage about the newness. That's still on the product page.

espressif_esp32_devkitc_v4_wroom_32e: fix title and name from WROVER (wrong)

---

assets/javascript/downloads.js

Typing any phrase in search bar on  "Blinka" page and then removing it does not correctly display all the cards.
The underlying issue is using `.split()` on `undefined`, which prevents the function from completing.
Spotted by @FoamyGuy during th Saturday stream: https://www.youtube.com/watch?v=8czmvgN3Q70&t=360s

Fix: TypeError while searching on Blinka page

---

_board/adafruit_feather_esp32s3_nopsram.md
_board/adafruit_qtpy_esp32s3_nopsram.md

Two ESP32-S3 boards did not include "8MB Flash" in their names. Do this explicitly.
Example of user confusion: https://discord.com/channels/327254708534116352/537365702651150357/1332080125835083839

include how much flash in 8MB no psram ESP32-S3 board names

---

_board/spotpear_esp32c3_lcd_1_44.md

User had trouble using circuitpython.org installer: https://forums.adafruit.com/viewtopic.php?t=216227.
Turns out chip family designator was `esp32` instead of `esp32c3`.

Fix family for spotpear_esp32c3_lcd_1_44.jpg

---

_board/adafruit_feather_esp32_v2.md

.. since this word is associated with the Feather ESP32 and is shown in large letters on the bottom of the V2 board.

Make Feather ESP32 V2 show up in search for "huzzah"

---

libraries/index.html

As discussed in the weekly CircuitPython meeting, https://github.com/adafruit/adafruit-circuitpython-weekly-meeting/blob/main/2025/2025-02-03.md#2643-in-the-weeds, we will drop building 8.x bundles.
- This is on the checklist here: https://github.com/adafruit/circuitpython/issues/9001

drop 8.x bundles

---

_board/lilygo_tdisplay_s3.md

This updates the board to hopefully now offer full installation along with bootloader only options in the installer

Update lilygo_tdisplay_s3.md - specify bootloader now it's in tinyUF2

---

_board/waveshare_esp32_s3_eth.md
_board/waveshare_esp32_s3_matrix.md

Somehow the board descriptions of these two boards are swapped.

Exchange board description of waveshare_esp32_s3_matrix and waveshare_esp32_s3_eth

---

_data/bootloaders.json

I hadn't spotted the bootloader version was a defined value, and since adding the TDisplayS3 bootloader option it needs the latest tinyUF2 release to pick it up.
Otherwise currently stalls at downloading bootloader stage:
This should pick up https://github.com/adafruit/tinyuf2/releases/tag/0.21.0

Update bootloaders.json - tinyUF2 0.21.0

---

_board/lilygo_tqt_pro_nopsram.md
_board/lilygo_tqt_pro_psram.md

I just realized the boards didn't say why they were different in their titles.

Distinguish the the TQ-T Pro boards apart

---

_board/lilygo_tqt_pro_nopsram.md
_board/lilygo_tqt_pro_psram.md

Apparently I only changed the page title and not how it shows in the list of boards. I've verified this does actually fix it.

Distinguish the the TQ-T Pro boards apart (second try)

---

_includes/downloads/board_image.html
_includes/index/learn_block.html
assets/sass/base/_variables.scss
assets/sass/layout/_header.scss
assets/sass/layout/_header_mobile.scss
assets/sass/pages/_downloads.scss
assets/sass/pages/_espinstaller.scss
assets/sass/pages/_home.scss
index.html

Mostly for the smallest of screen sizes. Fixes some image resolution issues as well.

Some more clean up to the new design

---

_config.yml

Should help curate the home page a bit better so we can limit guides with blurry images or guides that are out of date, etc.

Add new filter to only use featured guides from circuitpython category

---

_board/firebeetle2_esp32s3.md
_board/yd_esp32_s3_n16r8.md

Added bootloader_id to:
- firebeetle2_esp32s3
- yd_esp32_s3_n16r8
Available in https://github.com/adafruit/tinyuf2/releases/tag/0.21.0

Add bootloader_id to some boards

---

_board/adafruit_vindie_s2.md
_board/firebeetle2_esp32s3.md
_board/lilygo_tdeck.md
_board/m5stack_cores3.md
_board/maker_badge.md
_board/seeed_xiao_esp32s3_sense.md
_board/smartbeedesigns_bee_motion_s3.md
_board/smartbeedesigns_bee_s3.md
_board/unexpectedmaker_bling.md
_board/unexpectedmaker_tinywatch_s3.md
_board/waveshare_esp32_s3_zero.md
_board/yd_esp32_s3_n16r8.md
_board/yd_esp32_s3_n8r8.md

I ran a script to list available bootloaders from tinyuf2 (0.21.0) on ESP32S2/3 and match with board ids, adding `bootloader_id` to those boards. There are maybe some more that could be added manually after checking that they are the right ones (like the `espressif_esp32s2_devkitc_1` variants).

Add a bunch of bootloader ID from tinyuf2

---

.github/workflows/adabot_cron.yml

This would serve as sort of "relief valve" for the long stalled actions task. The configuration is documented here: https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#jobsjob_idtimeout-minutes making it give up and get cancelled sooner if it gets stalled.
The default value is 360 which matches the 6 hours that the actions run lasts when it gets stalled. 
I believe with it set to 150 minutes it should get cancelled and stopped after 2.5 hours maximum instead of  6 hours. 
2.5 hours was selected to account for up to 2 of the 1hour wait intervals for API rate limit. I believe that should make it so that along with the fix from https://github.com/adafruit/adabot/pull/397 this should always be able to finish in under 2.5 hours under normal circumstances. …

Add timeout-minutes to adabot.update_cp_org_libraries action task

---

_data/files.json

Previous numbers were from S3 direct logs. Cloud front requests from S3 on cache miss only. The user agent was also cloud front instead of the actual requester. Cloud front logs have the actual user agent and we use it to filter out bot requests.
So, the old numbers (relatively) under counted popular boards and over counted boards that only bots cared about. These numbers should be truer to reality.

Switch to download counts from Cloud Front

---

_board/adafruit_feather_esp32_v2.md
_board/adafruit_feather_huzzah32.md

A few users have confused the original Feather HUZZAH32 and Fthe eather ESP32 V2. Add some cautionary text. The latest user with this issue also asked that the name include "HUZZA32" (which is on the bottom of the board).
I also added some alert boxes already in the two guides.
I deliberately took the link to the original HUZZAH32 Feather out of the description of the V2. I also removed some obsolete "it's early" language from the original description.

differentiate original Feather HUZZAH32 and Feather ESP32 V2

---

tools/generate-board-info.py

Fixes a typo introduced by #1653.

Fix doubled `//` in bootloader path

---

_board/m5stack_timer_camera_x.md

Removing camera tag and adding warning for camera use as per [Issue discussion](https://github.com/adafruit/circuitpython/issues/9907)

Update m5stack_timer_camera_x.md / remove Camera tag and added warning

---

_data/bootloaders.json
_includes/download/board.html

For CircuitPython 10, the ESP32-S2 and ESP32-S3 flash partition layouts have changed, to increase the size of the firmware partition. These changes are upward-compatible with CircuitPython 9.1.0 and up.  All the builds have now been updated to assume the new partition layout.
- Bump the TinyUF2 version for `esp32s2` and `esp32s3` to 0.3.50.
- Update and rewrite the Espressif bootloader install/update section, to make it clearer and point to external references.
Here is a screenshot of the revised section, for easier proofing:

Update espressif bootloader; update instrutions

---

_board/ai_on_the_edge_cam.md

Fixes an issue reported in discord: https://discord.com/channels/327254708534116352/327298996332658690/1422214092806033409
I tested this change locally by running dev server and confirming that the S3 button now leads to the proper page that contains firmware files instead of an empty list.

fix board_id for prokyber ai edge cam.
