adafruit/circuitpython-org

- _data/files.json
Some bug caused it to fail on Travis
> Update to count 3.1.2 downloads as well

- _layouts/download.html
Reverts adafruit/circuitpython-org#48
> Revert "Fix language dropdown to do non-en_US links"

- assets/javascript/downloads.js
- downloads.html
Search based on name, and not id.
> Fix searching on board names

- _board/pyportal.md
- _board/template.md
- assets/javascript/downloads.js
- assets/sass/base/_variables.scss
- assets/sass/layout/_header.scss
- assets/sass/pages/_download.scss
- assets/sass/pages/_downloads.scss
- assets/sass/pages/_home.scss
- downloads.html
Includes filtering and sorting on downloads page. Ability to add features to the boards. We should probably limit these somewhat so the UI doesn't become cluttered with too many features. Maybe travis could whitelist allowed features that can be added to boards. Also includes a few various fixes and tweaks.
Template includes example of how to add features, as well as pyportal having a few starting features.
Fixes: https://github.com/adafruit/circuitpython-org/issues/10
> Filtering and sorting functionality, various fixes

- .gitmodules
- _includes/header.html
- assets/css/main.scss
- assets/sass/pages/_awesome.scss
- awesome.html
Adds awesome link to header, and renders the awesome readme from the submodule.
Fixes #92.
> Awesome Content

- assets/css/main.scss
- assets/javascript/stats.js
- assets/sass/layout/_grid.scss
- assets/sass/pages/_awesome.scss
- assets/sass/pages/_home.scss
- assets/sass/pages/_stats.scss
- awesome.html
- index.html
- stats.html
Unlisted stats page on /stats. Uses github api to parse and populate the stats. Rework a bit of the css to share it a bit better.
Fixes: https://github.com/adafruit/circuitpython-org/issues/98
> Stats Page

- _data/libraries.json
Adding the JSON file for #119.
> Add '_data/libraries.json'

- .travis.yml
- Updates the adabot submodule, to bring in the `urllib3` vulnerability fix.
- Fixes the conditional in `.travis.yml`
> Update adabot & .travis.yml

- _data/libraries.json
Auto updates with `adabot` are still not working yet. Here's a manual update.
> Manual Update To '_data/libraries.json'

- _data/libraries.json
54 PRs merged!
_Hopefully we'll get the auto-updates straightened out this week._
> Manual '_data/libraries.json' Update

- index.html
~the~ Damien George → Damien George  
~it's~ libraries → **its** libraries
~it's~ documentation → **its** documentation
> Fix a few typos in the Thanks section

- _board/pygamer.md
Add description and link to where the product is shown in New Products on YouTube.
> Add PyGamer description

- _board/pybadge.md
Added description text and link to the New Products Youtube instead of Top Secret.
> Update pybadge with description text

- _data/libraries.json
One more manual update, as adabot is still buggy.
> libraries.json Update

- _includes/header.html
> Added Blinka Linka

- _blinka/raspberry_pi_1a.md
I noticed this while looking at all the Blinka boards.
> Fix Raspberry Pi 1 Model A image

- _board/robohatmm1_m0.md
- _board/robohatmm1_m4.md
In this pull request:
- added robohat m4
- updated robohat m0 to reflect name changes in circuitpython
> Robo HAT MM1 M0 & M4

- _board/circuitplayground_bluefruit.md
- _board/robohatmm1_m4.md
> fix CPB image filename; fixe robhatmm1_m4 file fields

- _data/files.json
Automated website update for release 5.0.0-alpha.2 by Blinka.
> Automated website update for release 5.0.0-alpha.2

- _board/monster_m4sk.md
Haven't updated any of the boards before, so I'm guessing on what needed to be fixed.
Thanks to @jedgarpark for pointing this out!
> Update name to match board

- _board/pewpew_m4.md
I'm hoping this was the issue.
> Removed extra space from PewPew M4

- .travis.yml
Correct the directory creation from #293.
Travis reference: https://travis-ci.com/adafruit/circuitpython-org/jobs/237604885#L242
> Fix Travis 'mkdir'

- assets/sass/layout/_header.scss
General mobile menu clean up as well.
> Fixes #173 - help menu is chopped off at bottom

- .travis.yml
> Add Issue Label Data to libraries.json

- _board/itsybitsy_m0_express.md
- _board/itsybitsy_m4_express.md
- _board/sparkfun_qwiic_micro_no_flash.md
- _board/sparkfun_qwiic_micro_with_flash.md
Also added links to some existing itsy bitsy boards
> Fixed names on Sparkfun boards

- _data/files.json
Automated website update for release 5.0.0-beta.0 by Blinka.
New boards:
* winterbloom_sol
> Automated website update for release 5.0.0-beta.0

- _board/circuitplayground_bluefruit.md
- _board/electronut_labs_papyr.md
- _board/kicksat-sprite.md
- _board/metro_nrf52840_express.md
- _board/monster_m4sk.md
- _board/pyb_nano_v2.md
- _board/pyboard_v11.md
- _board/serpente.md
- _board/snekboard.md
- _board/sparkfun_qwiic_micro_no_flash.md
- _board/sparkfun_qwiic_micro_with_flash.md
- _board/spresense.md
- _board/stm32f407vg_discovery.md
- _board/stm32f411ve_discovery.md
- _board/stm32f412zg_discovery.md
- _board/stringcar_m0_express.md
- _board/winterbloom_sol.md
This should leave it at 10 features.
> Pared down Features list

- _data/files.json
Automated website update for release 4.1.1 by Blinka.
New boards:
* teknikio_bluebird
* xinabox_cc03
* xinabox_cs11
* stm32f411ce_blackpill
> Automated website update for release 4.1.1

- _data/files.json
This will fix #343 for now. I've submitted an issue to circuitpython to fix the issue permanently.
> Fix robohatmm1 unknown board

- blinka.html
With the other PR in place now, this fixes #347. Tested with Jekyll on my system locally.
> Added board counter for Blinka page

- _config.yml
- _includes/head.html
- _includes/metadata.html
Also includes: https://github.com/adafruit/circuitpython-org/issues/365
> Metadata - Includes initial twitter cards and open graph and some clean up

- _includes/header.html
- _includes/header_mobile.html
Newsletter link added to the very top nav.
> fixes #372 - add newsletter to top nav

- .github/workflows/build.yml
> Adding bundler install to github actions Workflow to fix error

- _data/files.json
Automated website update for release 5.0.0-beta.5 by Blinka.
New boards:
* feather_bluefruit_sense
* ndgarage_ndbit6
* meowbit_v121
* teensy40
* imxrt1060_evk
* imxrt1020_evk
> Automated website update for release 5.0.0-beta.5

- _data/files.json
Automated website update for release 5.0.0-rc.1 by Blinka.
> Automated website update for release 5.0.0-rc.1

- _data/files.json
Automated website update for release 5.0.0 by Blinka.
> Automated website update for release 5.0.0

- _blinka/beaglebone_black_wireless.md
I noticed this after my PR was merged.
> Updated Beaglebone Black Wireless Manufacturer

- _data/files.json
Created locally with this script: https://gist.github.com/tannewt/7e396947ef1b91dd50cd4cab2dac902c
cc @sommersoft
> Add download counts

- _data/files.json
Automated website update for release 5.1.0 by Blinka.
> Automated website update for release 5.1.0

- _data/files.json
Automated website update for release 5.2.0 by Blinka.
New boards:
* bdmicro_vina_m0
* 8086_commander
* winterbloom_big_honking_button
* thunderpack
* fomu
> Automated website update for release 5.2.0

- _board/fomu.md
Update the manufacturer of Fomu to Sean 'xobs' Cross.
> fomu: fix manufacturer name

- _data/files.json
Automated website update for release 5.3.0 by Blinka.
> Automated website update for release 5.3.0

- _board/teensy41.md
I saw the new Adafruit product page for Teensy 4.1, so I updated board to match.
> Updated Teensy 4.1 with Adafruit product info

- assets/javascript/downloads.js
Fixes #458. Github issues are reporting fixed, so maybe it will work this time.
> Fixed Date sorting

- _board/aloriumtech_evo_m51.md
Fixed a typo and modified the features list a bit in the _board .md file.
> Typo fix, minor edits

- _board/hiibot_bluefi.md
> Re-remove extra line in hiibot bluefi board

- _board/hiibot_bluefi.md
Reverts adafruit/circuitpython-org#483
@BradChan
> Show hiibot bluefi now that it's added to CircuitPython

- _data/files.json
- _includes/download/board.html
- assets/sass/pages/_download.scss
Fixes #426 
Example of page render here: https://github.com/adafruit/circuitpython-org/issues/426#issuecomment-650640474
@jwcooper, please let me know if my CSS edits aren't correct. I've never used Sass before, so I took a guess...
Updates to `_data/files.json` were "manual" for this PR, but the release PRs from the core repo should include future changes. See [circuitpython #3087](https://github.com/adafruit/circuitpython/pull/3087).
> Include The Available Built-in Modules For Each Board

- _board/pewpew_m4.md
* Better description
* Warning about updating beyond 6.x
* Purchase links
> pewpew_m4: update description

- _board/espruino_wifi.md
> Add Wifi warning to Espruino_wifi

- Gemfile
Fix contributing page loading json from s3.
> Add json gem into jekyll_plugins group

- _board/matrixportal_m4.md
Changed Matricies to Matrices.
> Fixed typo in MatrixPortal M4

- _board/bast_pro_mini_m0.md
I noticed this just after merging #559
> Unhiding bast pro mini

- _board/unexpectedmaker_feathers2.md
- _board/unexpectedmaker_feathers2_prerelease.md
and feathers2.io web link so visitors can get more info
Also added purchase links to final board on the pre-release page.
> Added Adafruit store purchase links

- _board/clue_nrf52840_express.md
.. a feature not actually present slipped in
> clue: update features list

- _board/electroniccats_bastwifi.md
- _board/unexpectedmaker_feathers2.md
- _board/unexpectedmaker_feathers2_prerelease.md
This was causing an additional 3 features to be added.
> Remove non-standard features from list

- .github/workflows/adabot_cron.yml
> allow the adabot_cron to be run on demand

- _board/unexpectedmaker_feathers2.md
simple typo, no need for separate issue?
> Fix spelling typo of "purchase" in unexpectedmaker_feathers2.md

- _board/seeeduino_xiao.md
There were multiple English abnormalities in the Seeduino Xiao description. I fixed them.
> Grammar fixes in Seeduino Xiao description

- _data/files.json
Automated website update for release 6.1.0-rc.0 by Blinka.
New languages:
* nl
* en_US
* hi
* pt_BR
* fr
* es
* ja
* sv
* el
* en_x_pirate
* cs
* fil
* de_DE
* ID
* ko
* pl
* it_IT
> Automated website update for release 6.1.0-rc.0

- .github/workflows/build.yml
> Fix dependency issue

- _includes/header.html
- _includes/header_mobile.html
- _layouts/default.html
- assets/sass/layout/_header.scss
Small header and site-wide a11y updates.
1. Added skip link
2. Updated header navigation color contrast
3. Added aria-labels to icon links in header
4. Added current page label in header navigation
> [a11y] Small updates to header: skip links, navigation color contrast

- _data/files.json
> fix files.json trailing commas

- _data/files.json
Automated website update for release 6.2.0 by Blinka.
> Automated website update for release 6.2.0

- assets/javascript/downloads.js
> update the URL with feature filters

- assets/javascript/downloads.js
Fixes: https://github.com/adafruit/circuitpython-org/issues/674
> Alphabetize filters

- assets/sass/pages/_downloads.scss
- blinka.html
- downloads.html
Fixes https://github.com/adafruit/circuitpython-org/issues/673
> fixes adafruit/circuitpython-org#673 - label filter button more clearly

- _board/winterbloom_big_honking_button.md
It seems that there was a copy-paste from another board that was not updated.
> Update BHB description

- _board/unexpectedmaker_feathers2.md
- _board/unexpectedmaker_tinys2.md
Just added purchase links for Unexpected maker TinyS2 and updated links for FeatherS2
> Updated purchase links for UM FeatherS2 and TinyS2

- _data/files.json
Automated website update for release 6.3.0 by Blinka.
> Automated website update for release 6.3.0

- _board/espressif_kaluga_1.3.md
- _board/espressif_kaluga_1.md
> Fix flash size on Kaluga boards

- _data/files.json
Automated website update for release 7.0.0-alpha.5 by Blinka.
New boards:
* microbit_v2
> Automated website update for release 7.0.0-alpha.5

- _data/files.json
Automated website update for release 7.0.0-rc.2 by Blinka.
New boards:
* challenger_rp2040_wifi
> Automated website update for release 7.0.0-rc.2

- _data/files.json
Automated website update for release 7.0.0-rc.3 by Blinka.
> Automated website update for release 7.0.0-rc.3

- _board/melopero_shake_rp2040.md
Also fixed a bit of formatting.
> Fix Melopero Shake RP2040 use of smart quotes

- connect/index.md
This includes TestFlight links for the apps.
> Add overview page that enumerates ways to connect

- downloads.html
Fixes: https://github.com/adafruit/circuitpython-org/issues/586
> Update /downloads meta description

- _layouts/common.html
- _layouts/contributing.html
- assets/css/main.scss
- assets/sass/pages/_common.scss
- assets/sass/pages/_contributing.scss
- assets/sass/pages/_libraries.scss
- awesome.html
- connect/index.md
- libraries/contributing/index.html
- libraries/index.html
This PR adds a common layout for content type pages. The /connect page is now styled to match the other content pages as well.
> Common layout and style connect page

- _includes/download/board.html
> Fix aliased board download links

- _data/files.json
Automated website update for release 7.1.0-beta.2 by Blinka.
New boards:
* cytron_maker_nano_rp2040
> Automated website update for release 7.1.0-beta.2

- _data/files.json
Automated website update for release 7.1.0-beta.3 by Blinka.
> Automated website update for release 7.1.0-beta.3

- _data/files.json
Automated website update for release 7.1.0-rc.0 by Blinka.
> Automated website update for release 7.1.0-rc.0

- _data/files.json
Automated website update for release 7.1.0-rc.1 by Blinka.
> Automated website update for release 7.1.0-rc.1

- _data/files.json
Automated website update for release 7.1.0 by Blinka.
> Automated website update for release 7.1.0

- _board/adafruit_qtpy_esp32s2.md
> Add info for QT Py ESP32S2

- _includes/download/board.html
> Add Turkish to language dropdowns

- _data/files.json
Automated website update for release 7.1.1 by Blinka.
> Automated website update for release 7.1.1

- _board/ai_thinker_esp_12k_nodemcu.md
Remove the part that was copied from the product description from the website mentioned below.
> Remove content

- _board/seeeduino_xiao_rp2040.md
Also, add "stretch" the content by adding a list and some breaks.
> Add tutorial section

- _board/stm32f411ce_blackpill.md
> Switch to unordered lists

- _data/files.json
Automated website update for release 7.2.0-rc.0 by Blinka.
New boards:
* hiibot_iots2
* ai_thinker_esp32-c3s-2m
> Automated website update for release 7.2.0-rc.0

- _data/files.json
Automated website update for release 7.2.0-rc.2 by Blinka.
> Automated website update for release 7.2.0-rc.2

- _board/lilygo_ttgo_t8_s2_st7789.md
> Switch from formatting style

- _board/aloriumtech_evo_m51.md
> Add more details

- _board/uchip.md
A couple of notes from my experience with the Itaca uChip.
> Additional Notes for the Itaca uChip

- _data/files.json
Automated website update for release 7.2.2 by Blinka.
> Automated website update for release 7.2.2

- _board/bdmicro_vina_d21.md
- _board/bdmicro_vina_d51.md
- _board/bdmicro_vina_d51_pcb7.md
- Spec were moved down and synced with vendor page
- Links
- Update formatting of list to improve readability
CC @bd34n
> Update docs for VINA-D51

- _board/stm32f411ce_blackpill_with_flash.md
- Make list unordered
- Move ALiexpress link to "Purchase"
> Update list formatting

- _board/pca10059.md
Add technical details from https://www.nordicsemi.com/Products/Development-hardware/nrf52840-dongle as list.
> Add technical details

- _board/lolin_s2_mini.md
Also, add a space between the value and the unit of measurement (follow the SI standard).
> Add intro, fix table formatting

- _data/files.json
Automated website update for release 7.2.4 by Blinka.
> Automated website update for release 7.2.4

- _data/files.json
Automated website update for release 7.2.5 by Blinka.
> Automated website update for release 7.2.5

- _data/files.json
Automated website update for release 7.3.0-beta.1 by Blinka.
> Automated website update for release 7.3.0-beta.1

- _board/unexpectedmaker_feather3.md
- _board/unexpectedmaker_pros3.md
- _board/unexpectedmaker_tinys3.md
Plus bolded some features for the ProS3
> Added purchase links for TinyS3, ProS3 & FeatherS2

- _board/bast_pro_mini_m0.md
Add technical details, update title and add links to details
Source: https://electroniccats.com/store/bast-pro-mini-m0/
> Add technical details and links to details

- _data/files.json
Automated website update for release 7.3.0-beta.2 by Blinka.
New boards:
* sparkfun_teensy_micromod
* elecfreaks_picoed
* wiznet_w5100s_evb_pico
* pimoroni_motor2040
> Automated website update for release 7.3.0-beta.2

- _blinka/adafruit_feather_rp2040.md
- _blinka/adafruit_qtpy_rp2040.md
- check-features.py
> Update Check Features to check Blinka boards too

- _board/adafruit_qtpy_esp32c3.md
- _board/adafruit_qtpy_esp32s2.md
- _board/adafruit_qtpy_esp32s3_nopsram.md
- _board/adafruit_qtpy_rp2040.md
- _board/qtpy_m0.md
- _board/qtpy_m0_haxpress.md
- _board/seeeduino_xiao.md
- template.md
Is this the best 'spelling' for the feature? Is it worth adding at all?
Closes adafruit/circuitpython#6371
Also updates awesome-circuitpython to latest
> Add "Xiao / QTPy Form Factor" feature

- _board/Seeed_XIAO_nRF52840_Sense.md
- _board/seeeduino_xiao_kb.md
- _board/seeeduino_xiao_rp2040.md
Also I didn't go through the features they could have, but at least made "breadboard-friendly" consistent.
> More Xiaos that have the Xiao form factor

- .github/workflows/build.yml
> Always update awesome-circuitpython during build

- check-images.py
This change will catch incorrect file names like in #985.
> Update checker script to fail if images are missing

- README.md
> Update README with link to Learn and image size details

- _board/lolin_s2_mini.md
Fixed silently in new sold boards.
https://macsbug.wordpress.com/2021/09/18/bug-report-for-s2-mini-v1-0-0/
> Update error on lolin s2 silkscreen

- assets/css/webworkflow.css
Reverted back to "white" scheme so we don't have everyone testing webworkflow stuck in dark mode ;)
> removing my test css

- .gitignore
- index.html
Shouldn't need to update the URL again.
> Update CP Day URL, .gitignore.

- _board/adafruit_feather_esp32_v2.md
From discussion in Discord after Kattni couldn't find the "ESP32 V2".
> Update ESP32 V2 title to make it easier to search for

- contributing/open_issues.html
> Fix duplicate Hacktoberfest label

- _config.yml
- _includes/downloads/board_image.html
- _layouts/download.html
> Original images are no longer deployed

- _includes/downloads/board_image.html
- _layouts/download.html
> Fix images

- _board/microdev_micro_c3.md
- _board/microdev_micro_s2.md
This PR contains changes to the description of the boards.
> Update MicroDev Boards

- _board/arduino_nano_rp2040_connect.md
> Nano Connect is "first" connected RP2040 board

- _board/brainboardz_neuron.md
As per https://github.com/adafruit/circuitpython/pull/7530#issuecomment-1419878011
> Hide brainboardz_neuron for now

- .github/workflows/adabot_cron.yml
- .github/workflows/build.yml
- .github/workflows/images.yml
Updates CI to use actions running on Node.js 16 to avoid deprecation
> Update actions to use Node.js 16

- _board/arduino_nano_33_ble.md
Related to https://github.com/adafruit/circuitpython-org/issues/410
> Add note on Nano 33 BLE Sense

- .github/workflows/build.yml
And also the secret had the wrong name, in Settings
> set user_email for pages build

- _data/files.json
Automated website update for release 8.2.5 by Blinka.
> Automated website update for release 8.2.5

- _board/warmbit_bluepixel.md
- api/boards.json
Fixes #1299. Also, fixed one of the hidden boards' board_url format.
> Fix board API output

- _board/unexpectedmaker_bling.md
- _board/unexpectedmaker_blizzard_s3.md
- _board/unexpectedmaker_feathers2.md
- _board/unexpectedmaker_feathers2_neo.md
- _board/unexpectedmaker_feathers2_prerelease.md
- _board/unexpectedmaker_feathers3.md
- _board/unexpectedmaker_nanos3.md
- _board/unexpectedmaker_pros3.md
- _board/unexpectedmaker_tinyc6.md
- _board/unexpectedmaker_tinypico.md
- _board/unexpectedmaker_tinypico_nano.md
- _board/unexpectedmaker_tinys2.md
- _board/unexpectedmaker_tinys3.md
- _board/unexpectedmaker_tinywatch_s3.md
- Fixed/Updated store URLs
- Updated info on Antennas
- Added more info for TinyWATCH S3
> Updated UM board info.

- _board/m5stack_cardputer.md
- _includes/download/board.html
And include custom instructions for M5Stack Cardputer. 
Resolves: #1406
> support custom bootloader entry instructions

- _board/autosportlabs_esp32_can_x2.md
Fixed links to: https://github.com/autosportlabs/ESP32-CAN-X2
> Fixed links to wiki for ESP32-CAN-X2

- _board/m5stack_dial.md
The Adafruit project page should probably also be updated to indicate that there is CircuitPython support but I don't know how to make that update.
> Update m5stack_dial.md with Adafruit purchase link

- _includes/download/board.html
- _layouts/download.html
- tools/generate-board-info.py
I think this is all that is needed to add the C6.
> Update to add installer for ESP32-C6

- index.html
> Updated sponsorship information

- _board/adafruit_feather_esp32c6_4mbflash_nopsram.md
> Update C6 Feather blurb

- _board/pca10056.md
> Remove castellated pads from pca10056

- _board/maker_badge.md
Updated links to purchase and GitHub code, corrected # of LEDs
> Updated links and info

- _data/bootloaders.json
> update bootloader version for atmel-samd

- _board/adafruit_esp32s3_camera.md
this allows it to be returned on searches for "pycam" or "pycamera"
> add pycamera tag to memento

- index.html
Update from 550 to 600 microcontrollers.
> Update count of supported microcontrollers

- libraries/index.html
Merge this after 10.x bundles are successfully built. Leaving as draft until then.
> Add 10.x bundles

- _includes/header.html
- Fixes #1618
Thanks @Neradoc for sleuthing
> Fix logo srcset for 3x

- _board/lilygo_tdongle_s3.md
> Fix title and name for lilygo t-dongle
